name: CI

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches: ["master"]
  push:
    branches: ["master"]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip${{ matrix.python }}-${{ hashFiles('Pipfile') }}
          restore-keys: ${{ runner.os }}-pip${{ matrix.python }}-
      - name: make sure we have version tags
        run: git fetch --unshallow --tags
      - name: Setup Virtualenv
        run: python -m venv .venv
      - name: Install
        run: source .venv/bin/activate && make requirements && python setup.py install
      - name: Lint
        run: source .venv/bin/activate && make flake black-check isort-check
      - name: Test
        run: source .venv/bin/activate && make tests
      - name: Upload Coverage
        run: .venv/bin/coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_FLAG_NAME: py${{ matrix.python }}
          COVERALLS_PARALLEL: true
          COVERALLS_SERVICE_JOB_ID: ${{ github.run_id }}

  coverage:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
      - name: Finalise Coverage
        run: pip3 install --upgrade coveralls && coveralls --service=github --finish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
