name: CI

on: # yamllint disable-line rule:truthy
  pull_request:
    branches: ["master"]
  push:
    branches: ["master"]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip${{ matrix.python }}-${{ hashFiles('Pipfile') }}
          restore-keys: ${{ runner.os }}-pip${{ matrix.python }}-
      - name: make sure we have version tags
        run: git fetch --unshallow --tags
      - name: Install pipenv
        run: python -m pip install --upgrade pip pipenv
      - name: Setup/install dependencies (pipenv)
        run: python -m pipenv install --dev
      - name: Lint (flake/black/isort)
        run: pipenv run make flake black-check isort-check
      - name: Test
        run: pipenv run make tests
      - name: Coveralls Parallel
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: py${{ matrix.python }}
          parallel: true
          format: cobertura
          debug: true

  coverage:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
      - name: Coveralls Finished
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
          format: cobertura
          carryforward: "run-3.9,run-3.10,run-3.11,run-3.12,run-3.13"
          debug: true
